--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/VorgeRyan/YetAnotherWarnPlugin
build-by-default: true
branches:
- main
projects:
  YetAnotherWarnPlugin:
    icon: meta\Warn.PNG
    path: YetAnotherWarnPlugin/
    libs:
      - src: jojoe77777/FormAPI/libFormAPI
        version: ^1.3.0
...
