--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/VorgeRyan/YetAnotherWarnPlugin
build-by-default: true
branches:
- main
projects:
  YetAnotherWarnPlugin:
    path: YetAnotherWarnPlugin/
...
