--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/VorgeRyan/YetAnotherWarnPlugin
build-by-default: true
branches:
- main
projects:
  YetAnotherWarnPlugin:
    path: YetAnotherWarnPlugin/
    libs:
      - src: jojoe77777/FormAPI
        version: ^1.3.0
...
