name: YetAnotherWarnPlugin
main: YetAnotherWarnPlugin\Main
author: VorgeRyan
version: 1.0.0
api: 3.14.0

extensions:
   Core: '>=7.4'

commands:
  warnp:
    description: "warn a player with this plugin"
    permission: use.warnp
